# Generated by Django 5.2.7 on 2025-12-03 20:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_update_donation_defaults'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at'], 'verbose_name': 'Donation', 'verbose_name_plural': 'Donations'},
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='core_donati_locatio_06edea_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='core_donati_donor_i_329f50_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='core_donati_status_f093a0_idx',
        ),
        migrations.RemoveIndex(
            model_name='donation',
            name='core_donati_created_ed4d90_idx',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='claimed_by',
        ),
        migrations.RemoveField(
            model_name='donation',
            name='quantity',
        ),
        migrations.AddField(
            model_name='donation',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donation',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='deleted_donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='donation',
            name='is_deleted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='donation',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='address',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='available_quantity',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donation_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='donation',
            name='donor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='donation',
            name='initial_quantity',
            field=models.PositiveIntegerField(),
        ),
        migrations.AlterField(
            model_name='donation',
            name='status',
            field=models.CharField(choices=[('available', 'Available'), ('claimed', 'Claimed'), ('rejected', 'Rejected')], default='available', max_length=20),
        ),
        migrations.AlterField(
            model_name='donation',
            name='title',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='location',
            name='name',
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
