# Generated by Django 5.0.7 on 2025-12-01 20:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_copy_quantity_data'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donation',
            options={'ordering': ['-created_at']},
        ),
        migrations.RenameIndex(
            model_name='donation',
            new_name='core_donati_locatio_06edea_idx',
            old_name='core_donation_location_idx',
        ),
        migrations.AlterField(
            model_name='location',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['donor'], name='core_donati_donor_i_329f50_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['status'], name='core_donati_status_f093a0_idx'),
        ),
        migrations.AddIndex(
            model_name='donation',
            index=models.Index(fields=['-created_at'], name='core_donati_created_ed4d90_idx'),
        ),
    ]
