# Generated by Django 5.2.7 on 2025-12-04 02:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_claim'),
    ]

    operations = [
        migrations.AddField(
            model_name='donation',
            name='deleted_quantity',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
